name: Deploy to Prod

on:
  push:
    branches:
      - main
      # TODO: Remove as soon as pipeline works
      - ci-cd/deploy-to-prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Recipe Finder
        run: |
          docker build \
            --build-arg SERVICE_DIR=recipe-finder-microservice \
            -t ghcr.io/${{ github.repository_owner }}/recipe-finder-microservice:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/recipe-finder-microservice:${{ github.sha }}

      - name: Build and push Store Checkout
        run: |
          docker build \
            --build-arg SERVICE_DIR=store-checkout-microservice \
            -t ghcr.io/${{ github.repository_owner }}/store-checkout-microservice:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/store-checkout-microservice:${{ github.sha }}

      - name: Build and push Store Items
        run: |
          docker build \
            --build-arg SERVICE_DIR=store-items-microservice \
            -t ghcr.io/${{ github.repository_owner }}/store-items-microservice:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/store-items-microservice:${{ github.sha }}
